name: Pull Request Cypress Tests

on:
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Install the application dependencies
      - name: Install dependencies
        run: yarn docker:build

      # Build the application
      - name: Run the application tests
        run: yarn docker:cypress
