name: Build and Deploy Server

on:
  pull_request:
    branches:
      - master
    types:
      - closed

env:
  SLACK_BOT_ACCESS_TOKEN: ${{ secrets.SLACK_BOT_ACCESS_TOKEN }}

jobs:
  deploy-server:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_API_KEY }}

      - run: |
          docker build -f packages/server/Dockerfile . -t chorusone/anthem:${{ github.sha }}
          docker push chorusone/anthem:${{ github.sha }}

      - name: Compute next SemVer tag
        id: semver
        uses: ChorusOne/semver-release-action@master
        with:
          release_branch: master
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker tag chorusone/anthem:${{ github.sha }} chorusone/anthem:latest
          docker push chorusone/anthem:latest
          docker tag chorusone/anthem:${{ github.sha }} chorusone/anthem:${{ steps.semver.outputs.tag }}
          docker push chorusone/anthem:${{ steps.semver.outputs.tag }}

      - uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NS: default
        with:
          args: set image deployment.apps/graphql -n $NS graphql=chorusone/anthem:${{ steps.semver.outputs.tag }}

      - uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NS: default
        with:
          args: rollout status -n $NS deployment/graphql

      # Send Slack notification if workflow succeeds
      # (docs: https://github.com/voxmedia/github-action-slack-notify-build)
      - name: Notify Slack on workflow success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_ACCESS_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C97TBFZFD # tech-updates channel
          status: SUCCESS
          color: good

      # Send Slack notification if workflow fails
      - name: Notify Slack on workflow failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_ACCESS_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C97TBFZFD
          status: FAILED
          color: danger
