name: Build and Deploy Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_API_KEY }}

      - working_directory: packages/server
        run: |
            docker build . -t chorusone/anthem:${{ github.sha }}
            docker push chorusone/anthem:${{ github.sha }}

      - name: Compute next SemVer tag
        id: semver
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - working_directory: packages/server
        run: |
            docker tag chorusone/anthem:${{ github.sha }} -t chorusone/anthem:latest
            docker push chorusone/anthem:latest
            docker tag chorusone/anthem:${{ github.sha }} -t chorusone/anthem:${{ steps.semver.outputs.tag }}
            docker push chorusone/anthem:${{ steps.semver.outputs.tag }}

      - uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NS: default
        with:
          args: set image deployment.apps/graphql -n $NS graphql=chorusone/anthem:${{ steps.semver.outputs.tag }}

      - uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NS: default
        with:
          args: rollout status -n $NS deployment/graphql
