name: Pull Request Tests

on:
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Setup NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Run build hook to trigger Netlify deployment
      - name: Deploy to Netlify
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f213b89bf4bb776769e0864

      # Run install and build steps
      - name: Build the application and run unit tests
        run: yarn docker:build

      # Run Cypress e2e tests
      - name: Run Cypress e2e tests
        run: yarn docker:cypress
