name: Pull Request Tests

on:
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Install Lerna CLI
      - name: Install Lerna
        run: npm i -g lerna

      # Install dependencies
      - name: Install dependencies
        run: lerna bootstrap

      # Build all packages
      - name: Build all packages
        run: yarn utils:build && yarn client:build && yarn server:build

      # Run unit tests for all packages
      - name: Run all package unit tests
        run: yarn test
