name: Pull Request Tests

on:
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Run build hook to trigger Netlify deployment
      - name: Deploy to Netlify
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f213b89bf4bb776769e0864
