name: Pull Request Tests

on:
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Run unit tests for all packages
      - name: Run project unit tests
        run: yarn test
