name: Pull Request Tests

on:
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Install the application dependencies
      - name: Install dependencies and build the application
        run: yarn docker:build

      # Build the application
      - name: Run all application tests
        run: yarn docker:cypress
